version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./code:/code
      - ./logs/nginx:/var/log/nginx
    links:
      - php
      - phpmyadmin
  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
    links:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ilidan
      MYSQL_USER: fanatik
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: myapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes:
      - ./sessions:/sessions
    links:
      - mysql:db
    ports:
      - "8080:80"
